### ISSUE TITLE
Installation falilure 

### ISSUE THREAD

**Issue by ghostmaster75** [ludiazv/node-nrf24#35]
i am trying to install the package on raspbian 11 bullseye 64bit - nodejs v14.19.1 but i have this error:

```
g++ -fPIC -marm -march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard -Ofast -Wall -pthread  -c RF24.cpp
g++: error: unrecognized command-line option ‘-marm’
g++: error: unrecognized command-line option ‘-mfpu=vfp’
g++: error: unrecognized command-line option ‘-mfloat-abi=hard’
make: *** [Makefile:42: RF24.o] Errore 1
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nrf24@0.1.7-beta preinstall: `./build_rf24libs.sh`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the nrf24@0.1.7-beta preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-25T14_52_04_566Z-debug.log
```

this is the log file

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'nrf24' ]
2 info using npm@6.14.16
3 info using node@v14.19.1
4 verbose npm-session 3fdf41ab69052fba
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/nrf24 1496ms (from cache)
8 silly pacote tag manifest for nrf24@latest fetched in 1594ms
9 timing stage:loadCurrentTree Completed in 2331ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 5ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 122ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule nrf24@0.1.7-beta checking installable status
17 http fetch GET 304 https://registry.npmjs.org/bindings 594ms (from cache)
18 silly pacote range manifest for bindings@^1.5.0 fetched in 642ms
19 silly resolveWithNewModule bindings@1.5.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/nan 633ms (from cache)
21 silly pacote range manifest for nan@^2.14.0 fetched in 666ms
22 silly resolveWithNewModule nan@2.15.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/nan-check 1093ms (from cache)
24 silly pacote version manifest for nan-check@0.0.6 fetched in 1122ms
25 silly resolveWithNewModule nan-check@0.0.6 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 191ms (from cache)
27 silly pacote version manifest for file-uri-to-path@1.0.0 fetched in 208ms
28 silly resolveWithNewModule file-uri-to-path@1.0.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/nan-marshal 808ms (from cache)
30 silly pacote version manifest for nan-marshal@0.0.5 fetched in 827ms
31 silly resolveWithNewModule nan-marshal@0.0.5 checking installable status
32 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2406ms
33 timing stage:loadIdealTree Completed in 2581ms
34 silly currentTree pi
34 silly currentTree ├── node-red-contrib-rpi-433@1.3.0
34 silly currentTree ├── q@1.5.1
34 silly currentTree ├── rpi-433-v3@1.2.0
34 silly currentTree └── underscore@1.13.2
35 silly idealTree pi
35 silly idealTree ├── bindings@1.5.0
35 silly idealTree ├── file-uri-to-path@1.0.0
35 silly idealTree ├── nan-check@0.0.6
35 silly idealTree ├── nan-marshal@0.0.5
35 silly idealTree ├── nan@2.15.0
35 silly idealTree ├── node-red-contrib-rpi-433@1.3.0
35 silly idealTree ├── nrf24@0.1.7-beta
35 silly idealTree ├── q@1.5.1
35 silly idealTree ├── rpi-433-v3@1.2.0
35 silly idealTree └── underscore@1.13.2
36 silly install generateActionsToTake
37 timing stage:generateActionsToTake Completed in 34ms
38 silly diffTrees action count 6
39 silly diffTrees add file-uri-to-path@1.0.0
40 silly diffTrees add nan@2.15.0
41 silly diffTrees add nan-marshal@0.0.5
42 silly diffTrees add bindings@1.5.0
43 silly diffTrees add nan-check@0.0.6
44 silly diffTrees add nrf24@0.1.7-beta
45 silly decomposeActions action count 48
46 silly decomposeActions fetch file-uri-to-path@1.0.0
47 silly decomposeActions extract file-uri-to-path@1.0.0
48 silly decomposeActions preinstall file-uri-to-path@1.0.0
49 silly decomposeActions build file-uri-to-path@1.0.0
50 silly decomposeActions install file-uri-to-path@1.0.0
51 silly decomposeActions postinstall file-uri-to-path@1.0.0
52 silly decomposeActions finalize file-uri-to-path@1.0.0
53 silly decomposeActions refresh-package-json file-uri-to-path@1.0.0
54 silly decomposeActions fetch nan@2.15.0
55 silly decomposeActions extract nan@2.15.0
56 silly decomposeActions preinstall nan@2.15.0
57 silly decomposeActions build nan@2.15.0
58 silly decomposeActions install nan@2.15.0
59 silly decomposeActions postinstall nan@2.15.0
60 silly decomposeActions finalize nan@2.15.0
61 silly decomposeActions refresh-package-json nan@2.15.0
62 silly decomposeActions fetch nan-marshal@0.0.5
63 silly decomposeActions extract nan-marshal@0.0.5
64 silly decomposeActions preinstall nan-marshal@0.0.5
65 silly decomposeActions build nan-marshal@0.0.5
66 silly decomposeActions install nan-marshal@0.0.5
67 silly decomposeActions postinstall nan-marshal@0.0.5
68 silly decomposeActions finalize nan-marshal@0.0.5
69 silly decomposeActions refresh-package-json nan-marshal@0.0.5
70 silly decomposeActions fetch bindings@1.5.0
71 silly decomposeActions extract bindings@1.5.0
72 silly decomposeActions preinstall bindings@1.5.0
73 silly decomposeActions build bindings@1.5.0
74 silly decomposeActions install bindings@1.5.0
75 silly decomposeActions postinstall bindings@1.5.0
76 silly decomposeActions finalize bindings@1.5.0
77 silly decomposeActions refresh-package-json bindings@1.5.0
78 silly decomposeActions fetch nan-check@0.0.6
79 silly decomposeActions extract nan-check@0.0.6
80 silly decomposeActions preinstall nan-check@0.0.6
81 silly decomposeActions build nan-check@0.0.6
82 silly decomposeActions install nan-check@0.0.6
83 silly decomposeActions postinstall nan-check@0.0.6
84 silly decomposeActions finalize nan-check@0.0.6
85 silly decomposeActions refresh-package-json nan-check@0.0.6
86 silly decomposeActions fetch nrf24@0.1.7-beta
87 silly decomposeActions extract nrf24@0.1.7-beta
88 silly decomposeActions preinstall nrf24@0.1.7-beta
89 silly decomposeActions build nrf24@0.1.7-beta
90 silly decomposeActions install nrf24@0.1.7-beta
91 silly decomposeActions postinstall nrf24@0.1.7-beta
92 silly decomposeActions finalize nrf24@0.1.7-beta
93 silly decomposeActions refresh-package-json nrf24@0.1.7-beta
94 silly install executeActions
95 silly doSerial global-install 48
96 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
97 verbose lock using /root/.npm/_locks/staging-8a58fe8d264b10c5.lock for /home/pi/node_modules/.staging
98 silly doParallel extract 6
99 silly extract file-uri-to-path@1.0.0
100 silly extract nan@2.15.0
101 silly extract nan-marshal@0.0.5
102 silly extract bindings@1.5.0
103 silly extract nan-check@0.0.6
104 silly extract nrf24@0.1.7-beta
105 silly tarball trying file-uri-to-path@1.0.0 by hash: sha512-0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==
106 silly tarball trying nan@^2.14.0 by hash: sha512-8ZtvEnA2c5aYCZYd1cvgdnU6cqwixRoYg70xPLWUws5ORTa/lnw+u4amixRS/Ac5U5mQVgp9pnlSUnbNWFaWZQ==
107 silly tarball trying nan-marshal@0.0.5 by hash: sha1-DUoDXpP0WsfyNhPZZjZ/QvsYLPY=
108 silly tarball trying bindings@^1.5.0 by hash: sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==
109 silly tarball trying nan-check@0.0.6 by hash: sha1-i/0uecNkOSgPpKl11BgkxaLSv6U=
110 silly tarball trying nrf24@latest by hash: sha512-gQhwg02H7QiwI+fdKP0h7m7K9kpQl0Q8YpaIaNQtBerGNVoD7RJPNeoM1ur3oze2uEQYGEegBFLZ96pns5a4vA==
111 timing audit submit Completed in 885ms
112 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 885ms
113 timing audit body Completed in 21ms
114 silly extract bindings@^1.5.0 extracted to /home/pi/node_modules/.staging/bindings-e015561d (847ms)
115 silly extract file-uri-to-path@1.0.0 extracted to /home/pi/node_modules/.staging/file-uri-to-path-4702ff23 (973ms)
116 silly extract nan-marshal@0.0.5 extracted to /home/pi/node_modules/.staging/nan-marshal-ebc6605b (1176ms)
117 silly extract nan-check@0.0.6 extracted to /home/pi/node_modules/.staging/nan-check-280695a4 (1275ms)
118 silly extract nan@^2.14.0 extracted to /home/pi/node_modules/.staging/nan-cbd23b3f (1468ms)
119 silly extract nrf24@latest extracted to /home/pi/node_modules/.staging/nrf24-79acc27a (1520ms)
120 timing action:extract Completed in 1547ms
121 silly doReverseSerial unbuild 48
122 silly doSerial remove 48
123 silly doSerial move 48
124 silly doSerial finalize 48
125 silly finalize /home/pi/node_modules/file-uri-to-path
126 silly finalize /home/pi/node_modules/nan
127 silly finalize /home/pi/node_modules/nan-marshal
128 silly finalize /home/pi/node_modules/bindings
129 silly finalize /home/pi/node_modules/nan-check
130 silly finalize /home/pi/node_modules/nrf24
131 timing action:finalize Completed in 103ms
132 silly doParallel refresh-package-json 6
133 silly refresh-package-json /home/pi/node_modules/file-uri-to-path
134 silly refresh-package-json /home/pi/node_modules/nan
135 silly refresh-package-json /home/pi/node_modules/nan-marshal
136 silly refresh-package-json /home/pi/node_modules/bindings
137 silly refresh-package-json /home/pi/node_modules/nan-check
138 silly refresh-package-json /home/pi/node_modules/nrf24
139 timing action:refresh-package-json Completed in 251ms
140 silly doParallel preinstall 6
141 silly preinstall file-uri-to-path@1.0.0
142 info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
143 silly preinstall nan@2.15.0
144 info lifecycle nan@2.15.0~preinstall: nan@2.15.0
145 silly preinstall nan-marshal@0.0.5
146 info lifecycle nan-marshal@0.0.5~preinstall: nan-marshal@0.0.5
147 silly preinstall bindings@1.5.0
148 info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
149 silly preinstall nan-check@0.0.6
150 info lifecycle nan-check@0.0.6~preinstall: nan-check@0.0.6
151 silly preinstall nrf24@0.1.7-beta
152 info lifecycle nrf24@0.1.7-beta~preinstall: nrf24@0.1.7-beta
153 verbose lifecycle nrf24@0.1.7-beta~preinstall: unsafe-perm in lifecycle false
154 verbose lifecycle nrf24@0.1.7-beta~preinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/node_modules/nrf24/node_modules/.bin:/home/pi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
155 verbose lifecycle nrf24@0.1.7-beta~preinstall: CWD: /home/pi/node_modules/nrf24
156 silly lifecycle nrf24@0.1.7-beta~preinstall: Args: [ '-c', './build_rf24libs.sh' ]
157 silly lifecycle nrf24@0.1.7-beta~preinstall: Returned: code: 2  signal: null
158 info lifecycle nrf24@0.1.7-beta~preinstall: Failed to exec preinstall script
159 timing action:preinstall Completed in 12057ms
160 verbose unlock done using /root/.npm/_locks/staging-8a58fe8d264b10c5.lock for /home/pi/node_modules/.staging
161 timing stage:rollbackFailedOptional Completed in 755ms
162 timing stage:runTopLevelLifecycles Completed in 19814ms
163 silly saveTree pi
163 silly saveTree ├─┬ node-red-contrib-rpi-433@1.3.0
163 silly saveTree │ └─┬ rpi-433-v3@1.2.0
163 silly saveTree │   ├── q@1.5.1
163 silly saveTree │   └── underscore@1.13.2
163 silly saveTree ├─┬ nrf24@0.1.7-beta
163 silly saveTree │ ├─┬ bindings@1.5.0
163 silly saveTree │ │ └── file-uri-to-path@1.0.0
163 silly saveTree │ ├─┬ nan-check@0.0.6
163 silly saveTree │ │ ├─┬ nan-marshal@0.0.5
163 silly saveTree │ │ │ └── nan@2.15.0
163 silly saveTree │ │ └── nan@2.15.0
163 silly saveTree │ └── nan@2.15.0
163 silly saveTree ├── q@1.5.1
163 silly saveTree ├── rpi-433-v3@1.2.0
163 silly saveTree └── underscore@1.13.2
164 warn enoent ENOENT: no such file or directory, open '/home/pi/package.json'
165 verbose enoent This is related to npm not being able to find a file.
166 warn pi No description
167 warn pi No repository field.
168 warn pi No README data
169 warn pi No license field.
170 verbose stack Error: nrf24@0.1.7-beta preinstall: `./build_rf24libs.sh`
170 verbose stack Exit status 2
170 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
170 verbose stack     at EventEmitter.emit (events.js:400:28)
170 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
170 verbose stack     at ChildProcess.emit (events.js:400:28)
170 verbose stack     at maybeClose (internal/child_process.js:1058:16)
170 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
171 verbose pkgid nrf24@0.1.7-beta
172 verbose cwd /home/pi
173 verbose Linux 5.10.103-v8+
174 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "nrf24"
175 verbose node v14.19.1
176 verbose npm  v6.14.16
177 error code ELIFECYCLE
178 error errno 2
179 error nrf24@0.1.7-beta preinstall: `./build_rf24libs.sh`
179 error Exit status 2
180 error Failed at the nrf24@0.1.7-beta preinstall script.
180 error This is probably not a problem with npm. There is likely additional logging output above.
181 verbose exit [ 2, true ]
```

**Comment by ludiazv** [comment]
Hi,
 The module uses a c++ library that have some problems on 64bit Raspi OS versions. I will look if there is any update now on this.

**Comment by ludiazv** [comment]
Updated to 0.2 version that solves the issue. It includes prebuilt binaries for node 12,14,16 & 17 for arm32 and arm64. Installation should be quite fast as the binaries are pre-compiled in the package.

**Comment by ghostmaster75** [comment]
Thank you very much!
